
import asyncio 
import numpy as np 
from aiofranka import RobotInterface, FrankaController
import time 
import json 

def decode_json(path): 

    data = json.load(path)
    print(data.keys())

async def main(data):
    robot = RobotInterface("172.16.0.2") 
    controller = FrankaController(robot)
    
    await controller.start()

    # tests the 1kHz connection with the robot 
    # prints average frequency / jitter 
    await controller.test_connection()

    init_pos = [0, 0, 0.3, -1.57079, 0, 1.57079, -0.7853]

    # this moves to certain position by offline trajectory generated by Ruckig
    await controller.move(init_pos)

    init_pos = data['episodes'][0]['achieved_joint_pos'][0]
    await controller.move(init_pos)

    # you can switch controllers / set gains at run-time 
    controller.switch("impedance")
    base =  np.array([1, 1, 1, 1, 0.6, 0.6, 0.6])

    controller.kp = base * 128.0
    controller.kd = base * 32.0
    # this enforces 50Hz update rate for impedance controller target
    controller.set_freq(50) 
    for cnt in range(len(data['episodes'][0]['commanded_joint_pos'])): 
        # delta = np.sin(cnt / 50.0 * np.pi) * 0.1
        # init = controller.initial_qpos
        target = data['episodes'][0]['commanded_joint_pos'][cnt]
        print(target)


        await controller.set("q_desired", target[:7])



if __name__ == "__main__":

    
    fp = "./examples/successful_rollouts_K128_D32.json"
    
    # load json 
    with open(fp, "r") as r: 
        data = json.load(r)

#    import pdb; pdb.set_trace(); 
#
    asyncio.run(main(data)) 
